export const ACTIONTYPES = {
    ADD_LISTINGS: "ADD_LISTINGS",
    FETCH_LISTINGS: "FETCH_LISTINGS",
    LISTINGS_LOADING: "LISTINGS_LOADING",
    LISTINGS_FAILED: "LISTINGS_FAILED",

    ADD_USERS: "ADD_USERS",
    FETCH_USERS: "FETCH_USERS",
    USERS_LOADING: "USERS_LOADING",
    USERS_FAILED: "USERS_FAILED"


}
